### PR TITLE
GHC 7.8 Compat

### LINKED ISSUE #2: building on ghc-7.8
Just a small wish, but any chance of getting microlens-aeson-2.1 to build on ghc-7.8?

```
[1 of 2] Compiling Lens.Micro.Aeson.Internal ( src/Lens/Micro/Aeson/Internal.hs, dist/build/Lens/Micro/Aeson/Internal.o )
src/Lens/Micro/Aeson/Internal.hs:33:30: Not in scope: ‘<$>’
src/Lens/Micro/Aeson/Internal.hs:34:23: Not in scope: ‘pure’
src/Lens/Micro/Aeson/Internal.hs:44:47: Not in scope: ‘<$>’
src/Lens/Micro/Aeson/Internal.hs:45:16: Not in scope: ‘pure’
src/Lens/Micro/Aeson/Internal.hs:55:58: Not in scope: ‘<$>’
src/Lens/Micro/Aeson/Internal.hs:56:19: Not in scope: ‘pure’
```
No is also okay, but if above is all then it could be quite easy.
Otherwise some upperbound (revision) should probably be added.

### PR DESCRIPTION
**Pull request by fosskers**
Closes #2

### CODE REVIEW

**Comment by juhp** [comment]
Thanks looks good to me.

I think you can relax the base package lower-bound to 4.6 then it also builds even with ghc-7.6.3. Yay :-)

**Comment by fosskers** [comment]
Let me double-check that.

**Comment by fosskers** [comment]
Hm, 7.6 seems to be considered ancient history as far as my build tools are concerned... let's call 7.8 the lower bound :)

**Comment by juhp** [comment]
I checked before posting my comment...

**Comment by fosskers** [comment]
Do you need 7.6 support? 7.8 was released Q1 of 2014, which is getting pretty old.

If it's just a matter of bumping the `base` bound down, then maybe it's not so bad. For me personally though, it's an issue that I can't verify it myself. Getting old compiler / cabal versions without using `stack` isn't so easy for me for technical / distro reasons. 

I suppose though, I can bump the bound down via a Hackage revision and let the [Hackage Matrix](https://matrix.hackage.haskell.org/#/package/microlens-aeson) prove you right ;)

**Comment by fosskers** [comment]
Bumped via a revision.

**Comment by fosskers** [comment]
@juhp there you go:

2019-01-01-120728_1918x1078_scrot

**Comment by juhp** [comment]
Wow, thanks so much!

Ah yes you use stack for your travis, which is very cool though.
